apiVersion: v1
kind: Service
metadata:
  labels:
    app: product-service
  name: product-service
  namespace: microservices
spec:
  ports:
  - name: http
    port: 8081
    targetPort: 8081
  selector:
    app: product-service
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: product-service
  name: product-service
  namespace: microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
      - env:
        - name: SERVER_PORT
          value: "8081"
        - name: SERVER_HOST
          value: 0.0.0.0
        - name: INVENTORY_SERVICE_HOST
          value: inventory-service
        - name: INVENTORY_SERVICE_PORT
          value: "50051"
        - name: APP_ENV
          valueFrom:
            configMapKeyRef:
              key: ENVIRONMENT
              name: microservices-config
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              key: LOG_LEVEL
              name: microservices-config
        image: groupthreesix.azurecr.io/product-service:568451a
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /health
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        name: product-service
        ports:
        - containerPort: 8081
        readinessProbe:
          httpGet:
            path: /health
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 200m
            memory: 256Mi
