apiVersion: v1
kind: Service
metadata:
  labels:
    app: order-service
  name: order-service
  namespace: microservices
spec:
  ports:
  - name: http
    port: 8082
    targetPort: 8082
  selector:
    app: order-service
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: order-service
  name: order-service
  namespace: microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - env:
        - name: SERVER_PORT
          value: "8082"
        - name: SERVER_HOST
          value: 0.0.0.0
        - name: APP_ENV
          valueFrom:
            configMapKeyRef:
              key: ENVIRONMENT
              name: microservices-config
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              key: LOG_LEVEL
              name: microservices-config
        image: groupthreesix.azurecr.io/order-service:d548a52
        livenessProbe:
          httpGet:
            path: /health
            port: 8082
          initialDelaySeconds: 15
          periodSeconds: 20
        name: order-service
        ports:
        - containerPort: 8082
        readinessProbe:
          httpGet:
            path: /health
            port: 8082
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 200m
            memory: 256Mi
