apiVersion: v1
kind: Service
metadata:
  labels:
    app: inventory-service
  name: inventory-service
  namespace: microservices
spec:
  ports:
  - name: grpc
    port: 50051
    targetPort: 50051
  selector:
    app: inventory-service
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: inventory-service
  name: inventory-service
  namespace: microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-service
  template:
    metadata:
      labels:
        app: inventory-service
    spec:
      containers:
      - env:
        - name: GRPC_PORT
          value: "50051"
        - name: GRPC_HOST
          value: 0.0.0.0
        - name: APP_ENV
          valueFrom:
            configMapKeyRef:
              key: ENVIRONMENT
              name: microservices-config
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              key: LOG_LEVEL
              name: microservices-config
        image: groupthreesix.azurecr.io/inventory-service:568451a
        imagePullPolicy: Always
        livenessProbe:
          initialDelaySeconds: 15
          periodSeconds: 20
          tcpSocket:
            port: 50051
        name: inventory-service
        ports:
        - containerPort: 50051
        readinessProbe:
          initialDelaySeconds: 5
          periodSeconds: 10
          tcpSocket:
            port: 50051
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 200m
            memory: 256Mi
